# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'ZMackay'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /ShootYourFriendsWebsite/projects/microbam
      - name: OurLegacy
        link: /ShootYourFriendsWebsite/projects/ourlegacy
  - name: Posts
    link: /
  - name: Tags
    link: /ShootYourFriendsWebsite/tags
  - name: About
    link: /ShootYourFriendsWebsite/about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/zmalexander
      - name: LinkedIn
        icon: linkedin-square
        link: inkedin.com/in/zach-mackay-b78b89170/
      - name: Twitter
        icon: twitter
        link: https://google.com
    
